### ISSUE TITLE
No message channels after clear data of my app

### ISSUE THREAD

**Issue by krystallii** [freshdesk/freshchat-android#26]
Hi, 

I'm getting this message "oops, no message channels here!" when I call showConversations.
The situation only happen when I clear data of my app in system setting, after kill and relaunch app it's become normal.

Below is my device information
Device: Sony G8142
Android Version: 7.1.1

**Comment by tryprasannan** [comment]
@krystallii Apologies for not getting back earlier. Can you help us with the following information
1) Where do you call Freshcht SDK's init() in the lifecycle of the app
2) Do you see this on all devices ? or specific devices?

**Comment by krystallii** [comment]
@tryprasannan Thanks for your reply

1. I call Freshcaht initialize in `onCreate`  of Application.
2. I saw this message on Sony G8142 and Sony Z5, but it is not showed this message every time after I clear data in system setting. I also tried Google Pixel 2, ASUS Zenfon3 ultra and Samsung Galaxy S8 and they showed normal.

**Comment by tryprasannan** [comment]
@krystallii How's the flow to launch support section setup in your app ? Are you launching the support activity as soon as you launch the app?

**Comment by MuthuFD** [comment]
Closing this issue as there is not enough info and thread is inactive.

@krystallii If you are still facing this issue, feel free to reopen this issue

**Comment by deathstroke007** [comment]
I am getting this error too. I have already initiated the conversation and get the restoreId and i save it somewhere. Now i clear the App data. I again login to the Application. When i call identifyuser() passing the same external id and the restoreid, i am getting the no channels. but when i click back and again call the code its working fine. I have demo implementation here.

oncreate of my Activity(Not the launcher activity) - 

```
FreshchatConfig freshchatConfig=new FreshchatConfig(App id, Appkey);
        freshchatConfig.setCameraCaptureEnabled(true);
        freshchatConfig.setGallerySelectionEnabled(true);

        Freshchat.getInstance(getApplicationContext()).init(freshchatConfig);
        FreshchatUser freshUser=Freshchat.getInstance(getApplicationContext()).getUser();

        freshUser.setFirstName("Aman");
        freshUser.setLastName("Verma");
        freshUser.setEmail("askjdnkjsan@gmail.com");
        freshUser.setPhone("+91", "9700000000");

//Call setUser so that the user information is synced with Freshchat's servers
        Freshchat.getInstance(getApplicationContext()).setUser(freshUser);
```

ONClick of a button - 

```
String external_ID = "testuser_aman";
        String restoreId = "a451f221-bcea-4fea-aa59-9215550a6261";

        Freshchat.getInstance(getApplicationContext()).identifyUser(external_ID, restoreId);
Freshchat.showConversations(getApplicationContext());

```

**Comment by deathstroke007** [comment]
When i click onback pressed from the SDK's Shwoconversations Activity and again click the button i am getting the previous conversations.

**Comment by MuthuFD** [comment]
Hi @deathstroke007 , Can you tell us what version of Freshchat SDK you are using?

**Comment by deathstroke007** [comment]
'com.github.freshdesk:freshchat-android:1.5.3' this version

**Comment by MuthuFD** [comment]
Recently we have released a fix for this issue.

Can you update to our latest SDK version 2.1.0.

**Comment by deathstroke007** [comment]
Okay sir. I will implement it and intimate you right away. Thanks

**Comment by deathstroke007** [comment]
It is still not working. After deleting the data and calling the identifyuser(external ,restore) shows no channels and when I press back and again click its working fine.

**Comment by deathstroke007** [comment]
Are you there??

**Comment by MuthuFD** [comment]
Hi @deathstroke007 , Please send us your query at support@freshchat.com. We can schedule a screen sharing session and debug this.

It will be helpful if you can share the list of Freshchat APIs used along with where in your Application flow they are being used.

**Comment by deathstroke007** [comment]
I have sent the query to the mentioned address. How to schedule a screen sharing session?

**Comment by MuthuFD** [comment]
@deathstroke007 Can you share the ticket id which you received.

**Comment by deathstroke007** [comment]
Hi Muthu. Thanks for supporting me back then. Also i am facing problem integrating the push notifications in Android. Which FCM server key should i add in the dashboard. I ahve added the FCM server key under project settings -> cloud messaging. But it is not working. Help

**Comment by MuthuFD** [comment]
@deathstroke007 Please use FreshchatNotificationConfig.launchActivityOnFinish API to set the activity to launch on the same task.

For more details refer section 7.2 [here](https://support.freshchat.com/support/solutions/articles/229319)

**Comment by deathstroke007** [comment]
Sir, I am using the same but it is creating another task. I find two instances of my Application.
